# Based on https://github.com/PrakashTrove/AWS-CodeBuild-NetCore/blob/master/buildspec.yml
# AWS CodeBuild spec to build an Elastic Beanstalk artifact for AWS CodePipeline to deploy
version: 0.2
    
phases:   
  install:
    runtime-versions:
      dotnet: 5.0
      
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore AuthenticationTutorial/AuthenticationTutorial.csproj
      - dotnet restore IdentityExample/IdentityExample.csproj
      
  build:
    commands:
      - echo Build started on `date`
      - dotnet build AuthenticationTutorial/AuthenticationTutorial.csproj
      - dotnet build IdentityExample/IdentityExample.csproj
      
  post_build:
    commands:
      - echo Publish started on `date`
      # https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/dotnet-linux-platform-bundle-app.html
      - dotnet publish -c Debug -r linux-x64 -o AuthenticationTutorial\bin\Debug\net5.0\linux-x64  AuthenticationTutorial/AuthenticationTutorial.csproj
      - dotnet publish -c Debug -r linux-x64 -o IdentityExample\bin\Debug\net5.0\linux-x64 IdentityExample/IdentityExample.csproj
      
artifacts:
  files:
    - '**/*'
