version: 0.2
    
phases:   
  install:
    runtime-versions:
      dotnet: 5.0 
 pre_build:
    commands:
      - echo Restore started on `date`    
       dotnet restore IdentityExample/IdentityExample.csproj
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -r linux-x64 IdentityExample/IdentityExample.csproj
artifacts:
  files:
    - IdentityExample/bin/Debug/net5.0/linux-x64/publish/**/*
  base-directory: './build_output'
