# Based on https://github.com/PrakashTrove/AWS-CodeBuild-NetCore/blob/master/buildspec.yml
# AWS CodeBuild spec to build an Elastic Beanstalk artifact for AWS CodePipeline to deploy
version: 0.2
    
phases:   
  install:
    runtime-versions:
      dotnet: 5.0 
 pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore WebApplicationSample/WebApplicationSample.csproj
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./build_output WebApplicationSample/WebApplicationSample.csproj
artifacts:
  files:
    - ./**/*
  base-directory: './build_output'
