version: 0.2
    
phases:   
  install:
    runtime-versions:
      dotnet: 5.0 
 pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore AuthenticationTutorial/AuthenticationTutorial.csproj
       dotnet restore IdentityExample/IdentityExample.csproj
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./build_output AuthenticationTutorial/AuthenticationTutorial.csproj
      - dotnet publish -c release -o ./build_output IdentityExample/IdentityExample.csproj
artifacts:
  files:
    - ./**/*
  base-directory: './build_output'
