# Based on https://github.com/PrakashTrove/AWS-CodeBuild-NetCore/blob/master/buildspec.yml
# AWS CodeBuild spec to build an Elastic Beanstalk artifact for AWS CodePipeline to deploy
version: 0.2
    
phases:   
  install:
    runtime-versions:
      dotnet: 5.0
      
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore AuthenticationTutorial.csproj
      - dotnet restore IdentityExample.csproj
      
  build:
    commands:
      - echo Build started on `date`
      - dotnet build AuthenticationTutorial.csproj
      - dotnet build IdentityExample.csproj
      
  post_build:
    commands:
      - echo Publish started on `date`
      # https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/dotnet-linux-platform-bundle-app.html
      - dotnet publish -c Release -r linux-x64 --self-contained false AuthenticationTutorial.csproj
      - dotnet publish -c Release -r linux-x64 --self-contained false IdentityExample.csproj
      
artifacts:
  files:
    - '**/*'
  base-directory: ./bin/Release/netcoreapp3.1/linux-x64/publish/
  discard-paths: no
